# ============================================
# 第1课：现代 LangChain 核心范式 —— LCEL 与 Runnable
#
# 课程目标：
# 1. 理解为什么现代 LangChain 抛弃旧版 LLMChain，转向 LCEL。
# 2. 掌握 Runnable 接口（invoke / stream / batch）及其工程意义。
# 3. 跑通第一条工程化的 Chain，并观察 Token 消耗。
#
# ⚠️ 成本提醒：
# - 默认使用 deepseek-chat，单价较低。
# - 本课演示用的 prompt 很短，预计单次消耗 < 500 tokens，花费约 0.001 元。
# - 如果你运行多次，费用会累积，建议控制在 5 次以内。
# ============================================

import time
from core.chains import build_qa_chain, build_explain_chain


def demo_01_basic_invoke():
    """
    演示1：基础调用 .invoke()
    
    .invoke() 是同步单条调用，适合：
    - 快速脚本
    - 需要立即拿到结果的场景（如 API 接口内部调用）
    """
    print("=" * 50)
    print("【演示1】基础调用 .invoke()")
    print("=" * 50)

    chain = build_qa_chain(temperature=0.3)

    # 输入是一个字典，key 对应 prompt 模板中的变量名 {question}
    question = "LangChain 是什么？"
    print(f"用户问题: {question}")
    print("正在请求 DeepSeek API，请稍候...")

    start = time.time()
    answer = chain.invoke({"question": question})
    elapsed = time.time() - start

    print(f"AI 回答: {answer}")
    print(f"耗时: {elapsed:.2f}s")
    print()


def demo_02_stream():
    """
    演示2：流式调用 .stream()
    
    .stream() 返回一个生成器，每次 yield 一段文本。
    工程意义：
    - Web 前端可以实时显示打字机效果，提升用户体验。
    - 减少用户感知的等待时间（First Token Latency）。
    """
    print("=" * 50)
    print("【演示2】流式调用 .stream()")
    print("=" * 50)

    chain = build_qa_chain(temperature=0.3)
    question = "用一句话说明 Python 的 GIL 是什么。"

    print(f"用户问题: {question}")
    print("AI 回答（流式）: ", end="", flush=True)

    for chunk in chain.stream({"question": question}):
        print(chunk, end="", flush=True)

    print("\n")


def demo_03_batch():
    """
    演示3：批量调用 .batch()
    
    .batch() 自动并发处理多条输入，内部有重试和限流。
    工程意义：
    - 后端处理批量任务（如批量生成摘要、批量审核）时效率更高。
    - 比手写 for-loop + thread pool 更简洁、更鲁棒。
    
    ⚠️ 注意：batch 会一次性发送多个请求，费用会叠加，请谨慎使用。
    """
    print("=" * 50)
    print("【演示3】批量调用 .batch()")
    print("=" * 50)

    chain = build_qa_chain(temperature=0.3)
    questions = [
        "什么是向量数据库？",
        "RAG 是什么意思？",
    ]

    print(f"批量输入: {questions}")
    print("正在并发请求，请稍候...")

    start = time.time()
    answers = chain.batch([{"question": q} for q in questions])
    elapsed = time.time() - start

    for q, a in zip(questions, answers):
        print(f"Q: {q}")
        print(f"A: {a}")
        print("-" * 30)

    print(f"总耗时: {elapsed:.2f}s")
    print()


def demo_04_runnable_protocol():
    """
    演示4：Runnable 接口的统一性
    
    无论你是 PromptTemplate、LLM、OutputParser，还是你自己写的函数，
    只要实现了 Runnable，都可以用 "|" 组合，并且都有 invoke/stream/batch 方法。
    
    这是 LangChain 架构的核心：统一接口带来可组合性。
    """
    print("=" * 50)
    print("【演示4】Runnable 协议与自定义组件")
    print("=" * 50)

    from langchain_core.runnables import RunnableLambda

    # 自定义一个 Runnable：给 AI 的回答加上时间戳和签名
    def add_signature(data: str) -> str:
        from datetime import datetime
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        return f"{data}\n\n[Generated by KnowledgeBase AI at {now}]"

    # RunnableLambda 把普通函数包装成 Runnable
    signature_step = RunnableLambda(add_signature)

    # 把签名组件拼到链的末尾
    base_chain = build_qa_chain()
    signed_chain = base_chain | signature_step

    question = "解释一下 Chain-of-Thought。"
    print(f"用户问题: {question}")
    result = signed_chain.invoke({"question": question})
    print(result)
    print()


if __name__ == "__main__":
    print("========================================")
    print("LangChain 第1课：LCEL 与 Runnable")
    print("讲师提示：请确保已在 config.py 中填入正确的 DeepSeek API Key")
    print("========================================\n")

    # 你可以取消注释想运行的演示：
    demo_01_basic_invoke()
    # demo_02_stream()
    # demo_03_batch()
    # demo_04_runnable_protocol()
